### ISSUE TITLE
3.11.0 master high cpu usage 100%

### ISSUE THREAD

**Issue by isolosun** [lizardfs/lizardfs#552] opened 2017-05-17 05:11 UTC
hi，
     after update lizardfs-master from 3.10.6 to 3.11.0，master process got high cpu usage，nearly 100%；
     strace shows : "
clock_gettime(CLOCK_MONOTONIC, {6124211, 29361630}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29390527}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29424178}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29454668}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29487454}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29520234}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29545317}) = 0
poll([{fd=5, events=POLLIN}, {fd=9, events=POLLIN}, {fd=13, events=POLLIN}, {fd=8, events=POLLIN}, {fd=10, events=POLLIN}, {fd=19, events=POLLIN}, {fd=15, events=POLLIN}, {fd=18, events=POLLIN}, {fd=17, events=POLLIN}, {fd=16, events=POLLIN}, {fd=14, events=POLLIN}, {fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=20, events=POLLIN}], 14, 0) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {6124211, 29619978}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29644542}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29669738}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29690135}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29719791}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29745405}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29774600}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29798960}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29826261}) = 0
clock_gettime(CLOCK_MONOTONIC, {6124211, 29850955}) = 0

";
     when switch master to shadow role，cpu usage down to normal；

**Comment by psarna** [comment] 2017-05-17 06:16
Duplicate of https://github.com/lizardfs/lizardfs/issues/547 , patch already exists and will be released soon

**Closed by psarna** 2017-05-17 06:16 UTC
Labels: duplicate

**Comment by isolosun** [comment] 2017-05-17 06:40
thx；
