### ISSUE TITLE
ignoregid not taken into account

### ISSUE THREAD

**Issue by xplodwild** [lizardfs/lizardfs#424] opened 2016-07-05 08:54 UTC
Hello,

I'm currently running LizardFS on production servers without any issue, until recently I had to do some deeper changes into the way we handle permissions. We're mostly doing Web hosting on those servers, so files all have permissions "sysadmin:www-data".

We recently needed to add another user to the www-data group so that he can do maintenance on the Web files as well, without having the sysadmin privileges, so we did a classic usermod on all nodes, so far so good. Except that when he tries to access a folder owned by sysadmin:www-data, he gets a Permission denied.

He logged out/back in, we've tried adding the "ignoregid" option, dismounting the mount points, restarting the master server+shadows and chunkservers, remounting back, but the "ignoregid" option seems to not enable.
The CGIServ stats of the mount points shows "ignoregid: no" on all 3 mount points we currently have, even though we've restarted all the lizardfs services multiple times, and remounted the mount points multiple times.

Here's our mfsexports.cfg:
```
xxx.xxx.xxx.xxx         /       rw,alldirs,maproot=0,ignoregid
xxx.xxx.xxx.yyy          /       rw,alldirs,maproot=0,ignoregid
xxx.xxx.xxx.zzz          /       rw,alldirs,maproot=0,ignoregid

# Allow meta
xxx.xxx.xxx.xxx          .       rw
xxx.xxx.xxx.yyy          .       rw
xxx.xxx.xxx.zzz          .       rw
```

Any idea what we could be missing? Are we hitting a bug?
Thanks!

**Comment by psarna** [comment] 2016-07-05 09:23
I just added an 'ignoregid' flag to my local installation and it worked 
fine, do you have any logs from syslog? If CGI states your mount point 
does not use 'ignoregid' then maybe something got parsed wrong. It 
shouldn't though, because I copy-pasted your mfsexports.cfg file and 
replaced xxx with IP addresses.
Similar issue was raised here, maybe it will provide you with some 
context: https://github.com/lizardfs/lizardfs/issues/295

**Comment by 4Dolio** [comment] 2016-07-05 11:10
Did you HUP the master service to reload the config? There is an even better util i can not recall which has a reload option.  Idk if a stop/start is required, i suspect not..

**Comment by onlyjob** [comment] 2016-08-07 02:29
Closing as duplicate of #295 and #265... I remember reporting similar problem long time ago and `ignoregid` was working for us ever since. IMHO it should be used by default.

**Closed by onlyjob** 2016-08-07 02:29 UTC
